name: CI

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup genpac
        run: |
          python -m pip install --upgrade pip
          pip install genpac

      - name: Create dist directory
        run: mkdir ./dist

      - name: Run genpac for Clash
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./clash.txt)" > ./dist/pac-clash.txt

      - name: Run genpac for SSR
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./ssr.txt)" > ./dist/pac-ssr.txt

      - uses: josStorer/get-current-time@v2
        id: time
        with:
          format: yyyy-MM-DD

      - name: Go to dist directory
        run: cd ./dist

      - name: Git Auto Commit
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout --orphan dist
          git add --all
          git commit --allow-empty -m "[${{ steps.time.outputs.formattedTime }}] update pac files" --no-verify --author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          git push origin dist --force
