name: CI

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - master


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup genpac
        run: |
          python -m pip install --upgrade pip
          pip install genpac

      - run: mkdir ./dist

      - name: Run genpac for Clash
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./clash.txt)" > ./dist/pac-clash.txt

      - name: Run genpac for SSR
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./ssr.txt)" > ./dist/pac-ssr.txt

      - uses: josStorer/get-current-time@v2
        id: time
        with:
          format: yyyy-MM-DD

      - run: cd ./dist

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[${{ steps.time.outputs.formattedTime }}] update pac files'
          branch: dist
          add_options: '--all'
          push_options: '--force'
          skip_dirty_check: true    
          create_branch: true
