name: CI

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup genpac
        run: |
          python -m pip install --upgrade pip
          pip install genpac

      - name: Run genpac for Clash
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./clash.txt)" > ./dist/pac-clash.txt

      - name: Run genpac for SSR
        run: genpac --format=pac --user-rule-from=rules.txt --pac-proxy="$(cat ./ssr.txt)" > ./dist/pac-ssr.txt

      - uses: josStorer/get-current-time@v2
        id: time
        with:
          format: yyyy-MM-DD

      - uses: EndBug/add-and-commit@v9
        with:
          message: "[${{ steps.time.outputs.formattedTime }}] update pac files"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
